---
title: "Residence Time"
author: "Jay T. Lennon, Nathan Wisnoski, Jaylen Beatty"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---
  
Analysis of community sequence data to test whether the structure and composition of bacterial communities is affected by extracellular DNA

# Setup Work Environment 
```{r}
# rm(list=ls())
getwd()
setwd("~/GitHub/2016_REU_Beatty/")
```

# Load data
```{r}
data <- read.csv("data/microscopy/final_cell_count_post.csv", sep = ",", header = TRUE)
str(data)
names(data)
summary(data)
attach(data)
shapiro.test(Residence.Time..hrs.)# p < .05, R.T. times are normally distributed
logRT= log(Residence.Time..hrs.)#Graph region cannot appropriately capture the wide gradient of R.T. values. Transformation makes this clearer.
shapiro.test(logRT)# p < .05, data is parametric
#Use Pearson's Product Moment for correlation.
```

#R.T. Vs. Total Cell Count. Logarithmic Transformation 
```{r}
logcount=log(DAPI.Count)
logcell=log(Cell_ml)
shapiro.test(logcell)# p < .05 Data is parametric.
shapiro.test(logcount)#p > .05. Data is nonparametric. 
#The data was transformed to linearize the graph.
#As opposed to transformation, Use Kendall's to test correlation.
```

#PLOT #1
```{r}
png("/Users/lennonj/GitHub/2016_REU_Beatty/figures/Density_RT.png", height = 1200, width = 1200, res = 192)
plot(logRT, logcell, 
     xlab = "", ylab = "", 
     xaxt = "n", yaxt = "n",
     cex = 2, pch = 16, xlim = log10(c(0.1, 1000)), ylim = c(4,10))
axis(side = 1, 
     labels = c(.1, 1, 10, 100, 1000),
     at = log10(c(.1, 1, 10, 100, 1000)), cex.lab = 1.5, lwd.ticks = 2.5)
axis(side = 2,
     las = 1, cex.lab = 1.5, lwd.ticks = 2)
axis(side = 3, at = log10(c(.1, 1, 10, 100, 1000)), labels = F, lwd.ticks = 2.5)
axis(side = 4, labels = F, lwd.ticks = 2.5)
box(lwd = 2.5)
abline(lm(logcell ~ logRT), lwd = 2.5)
mtext("Residence Time (Hours)", line = 3, side = 1, cex = 1.5)
mtext(expression("Bacterial Density" ~ (log[10] ~ cells ~ ml^{-1}) ), 
      line = 2.25, side = 2, cex = 1.2)
dev.off()

png("figures/Activity_RT.png", height = 1200, width = 1200, res = 192)
plot(logRT, X..Active, 
     xlab = "", ylab = "", 
     xaxt = "n", yaxt = "n",
     cex = 2, pch = 22, col = "black", bg = "white", lwd = 2, ylim = c(0,100), xlim = log10(c(.1, 1000)))
axis(side = 1, 
     labels = c(.1, 1, 10, 100, 1000),
     at = log10(c(.1, 1, 10, 100, 1000)), cex.lab = 3, lwd.ticks = 2)
axis(side = 2,
     las = 1, cex.lab = 3, lwd.ticks = 2)
axis(side = 3, at = log10(c(.1, 1, 10, 100, 1000)), labels = F, lwd.ticks = 2)
axis(side = 4, labels = F, lwd.ticks = 2)
box(lwd = 2)
abline(lm(X..Active ~ logRT), lwd = 2)
mtext("Residence Time (Hours)", line = 3, side = 1, cex = 1.5)
mtext(expression("Percent Activity"), 
      line = 2.25, side = 2, cex = 1.5)
dev.off()
```

#PLOT #2

# remove fastest residence time
```{r}
data2 <- data[data[,2]>0.4,]
par(mar = rep(2, 4))
total <- log10(data2$DAPI.Count)
tau <- log10(data2$Residence.Time..hrs.)
tau.2 <- tau^2
plot(tau,total)
quad.mod <-lm(total ~ tau + tau.2)

tauvalues <- seq(0, 2.5, 0.2)
pred.tot <- predict(quad.mod,list(tau=tauvalues, tau.2=tauvalues^2))
lines(tauvalues, pred.tot, col = "darkgreen", lwd = 3)
```


# Plot #3
```{r}
# Number of Dormant or Active Cells
tau <- log10(data$Residence.Time..hrs.)
act <- logcell * (X..Active/100)
dorm <- logcell * (1 -(X..Active/100))

png("figures/Active_abund_RT.png", height = 1200, width = 1200, res = 192)
plot(logRT, act, 
     xlab = "", ylab = "", 
     xaxt = "n", yaxt = "n",
     cex = 1.2, pch = 16, ylim = c(0,9), xlim = log10(c(.1, 1000)))
axis(side = 1, 
     labels = c(.1, 1, 10, 100, 1000),
     at = log10(c(.1, 1, 10, 100, 1000)), cex.lab = 1.5, lwd.ticks = 2)
axis(side = 2,
     las = 1, cex.lab = 1.5, lwd.ticks = 2)
axis(side = 3, at = log10(c(.1, 1, 10, 100, 1000)), labels = F, lwd.ticks = 2)
axis(side = 4, labels = F, lwd.ticks = 2)
box(lwd = 2)
abline(lm(act ~ logRT), lwd = 2)
mtext("Residence Time (Hours)", line = 3, side = 1, cex = 1.5)
mtext(expression("Active bacteria (cells/mL"), 
      line = 2.25, side = 2, cex = 1.5)
dev.off()
```

# Plot #4
```{r}
png("figures/Active-Total_RT.png", height = 1200, width = 1200, res = 192)

# plot total
plot(logRT, logcell, 
     xlab = "", ylab = "", 
     xaxt = "n", yaxt = "n",
     cex = 1.2, pch = 22, col = "black" xlim = log10(c(0.1, 1000)), ylim = c(0,10))
axis(side = 1, 
     labels = c(.1, 1, 10, 100, 1000),
     at = log10(c(.1, 1, 10, 100, 1000)), cex.lab = 1.5, lwd.ticks = 2)
axis(side = 2,
     las = 1, cex.lab = 1.5, lwd.ticks = 2)
axis(side = 3, at = log10(c(.1, 1, 10, 100, 1000)), labels = F, lwd.ticks = 2)
axis(side = 4, labels = F, lwd.ticks = 2)
box(lwd = 2)
abline(lm(logcell ~ logRT), lwd = 2)
mtext("Residence Time (Hours)", line = 3, side = 1, cex = 1.5)
mtext(expression("Density" ~ (log[10] ~ cells ~ ml^{-1}) ), 
      line = 2.25, side = 2, cex = 1.2)

points(logRT, act, col = "red")
abline(lm(act ~ logRT), lwd = 2, col = "red")
dev.off()
```
